//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioMexWCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BioMexDatabaseEntities1 : DbContext
    {
        public BioMexDatabaseEntities1()
            : base("name=BioMexDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FaceFeature> FaceFeatures { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<IdealFeature> IdealFeatures { get; set; }
    }
}
