CREATE TABLE Users
(
	US_ID INT IDENTITY NOT NULL PRIMARY KEY,
	US_NAME VARCHAR(MAX) NULL,
	US_SURNAME VARCHAR(MAX) NULL,
	US_USERNAME VARCHAR(MAX) NOT NULL,
	US_PASSWORD VARCHAR(MAX) NOT NULL,
	US_AGE INT NULL,
	US_UP_TO_DATE BIT NOT NULL,
	US_LAST_LOGGED_IN DATETIME NOT NULL,
	US_IS_ADMIN BIT NOT NULL,
)

-- ONE USER CAN HAVE MANY FEATURES
-- |
-- ONE TO MANY RELATIONSHIP
-- |

CREATE TABLE Features
(
	FE_ID INT IDENTITY NOT NULL PRIMARY KEY,
	US_ID INT NOT NULL,
	FE_TIME_TAKEN DATETIME NOT NULL,
	FE_TYPING_SPEED INT NOT NULL,
	FE_SHIFT_CLASS INT NOT NULL,
	FE_PASSWORD_COUNT INT NOT NULL,
	FOREIGN KEY (US_ID) REFERENCES Users (US_ID),
)

-- |
-- ONE TO ONE RELATIONSHIP
-- |
-- A TYPE OF FEATURE

CREATE TABLE PairedKeys
(
	PK_ID INT NOT NULL PRIMARY KEY,
	PK_1 INT NOT NULL,
	PK_2 INT NOT NULL,
	PK_3 INT NOT NULL,
	PK_4 INT NULL,
	PK_5 INT NULL,
	PK_6 INT NULL,
	PK_7 INT NULL,
	PK_8 INT NULL,
	PK_9 INT NULL,
	PK_10 INT NULL,
	FOREIGN KEY (PK_ID)   REFERENCES Features(FE_ID),
)

CREATE TABLE KeyOrder
(
	KO_ID INT NOT NULL PRIMARY KEY,
	KO_1 INT NOT NULL, 
	KO_2 INT NOT NULL,
	KO_3 INT NOT NULL,
	KO_4 INT NOT NULL,
	KO_5 INT NOT NULL,
	KO_6 INT NOT NULL,
	KO_7 INT NOT NULL,
	KO_8 INT NOT NULL,
	KO_9 INT NOT NULL,
	KO_10 INT NULL,
	KO_11 INT NULL,
	KO_12 INT NULL,
	KO_13 INT NULL,
	KO_14 INT NULL,
	KO_15 INT NULL,
	KO_16 INT NULL,
	KO_17 INT NULL,
	KO_18 INT NULL,
	KO_19 INT NULL,
	KO_20 INT NULL,
	FOREIGN KEY (KO_ID) REFERENCES Features(FE_ID),
)

CREATE TABLE KeyLatencies
(
	KL_ID INT NOT NULL PRIMARY KEY,
	KL_1 INT NOT NULL, 
	KL_2 INT NOT NULL,
	KL_3 INT NOT NULL,
	KL_4 INT NOT NULL,
	KL_5 INT NOT NULL,
	KL_6 INT NOT NULL,
	KL_7 INT NOT NULL,
	KL_8 INT NOT NULL,
	KL_9 INT NOT NULL,
	KL_10 INT NULL,
	KL_11 INT NULL,
	KL_12 INT NULL,
	KL_13 INT NULL,
	KL_14 INT NULL,
	KL_15 INT NULL,
	KL_16 INT NULL,
	KL_17 INT NULL,
	KL_18 INT NULL,
	KL_19 INT NULL,
	KL_20 INT NULL,
	FOREIGN KEY (KL_ID) REFERENCES Features(FE_ID),
)

CREATE TABLE KeyPress
(
	KP_ID INT NOT NULL PRIMARY KEY,
	KP_1 INT NOT NULL, 
	KP_2 INT NOT NULL,
	KP_3 INT NOT NULL,
	KP_4 INT NOT NULL,
	KP_5 INT NOT NULL,
	KP_6 INT NOT NULL,
	KP_7 INT NOT NULL,
	KP_8 INT NOT NULL,
	KP_9 INT NOT NULL,
	KP_10 INT NULL,
	KP_11 INT NULL,
	KP_12 INT NULL,
	KP_13 INT NULL,
	KP_14 INT NULL,
	KP_15 INT NULL,
	KP_16 INT NULL,
	KP_17 INT NULL,
	KP_18 INT NULL,
	KP_19 INT NULL,
	KP_20 INT NULL,
	FOREIGN KEY (KP_ID) REFERENCES Features(FE_ID),
)


-- |
-- ONE TO ONE RELATIONSHIP
-- |
-- A TYPE OF FEATURE


CREATE TABLE FaceFeature
(
	FF_ID INT NOT NULL PRIMARY KEY,
	FF_X_COORDINATE INT NOT NULL,
	FF_Y_COORDINATE INT NOT NULL,
	FF_DESCRIPTOR VARCHAR(MAX) NOT NULL,
	FOREIGN KEY (FF_ID)   REFERENCES Features(FE_ID),
)

