//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioMexWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int FE_ID { get; set; }
        public int US_ID { get; set; }
        public System.DateTime FE_TIME_TAKEN { get; set; }
        public int FE_TYPING_SPEED { get; set; }
        public int FE_SHIFT_CLASS { get; set; }
        public int FE_PASSWORD_COUNT { get; set; }
        public string FE_KEY_PRESS_DURATION { get; set; }
        public string FE_KEY_LATENCIES { get; set; }
        public string FE_KEY_ORDER { get; set; }
        public string FE_PAIRED_KEYS { get; set; }
    
        public virtual FaceFeature FaceFeature { get; set; }
        public virtual User User { get; set; }
    }
}
