//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioMexWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyLatency
    {
        public int KL_ID { get; set; }
        public int KL_1 { get; set; }
        public int KL_2 { get; set; }
        public int KL_3 { get; set; }
        public int KL_4 { get; set; }
        public int KL_5 { get; set; }
        public int KL_6 { get; set; }
        public int KL_7 { get; set; }
        public int KL_8 { get; set; }
        public int KL_9 { get; set; }
        public Nullable<int> KL_10 { get; set; }
        public Nullable<int> KL_11 { get; set; }
        public Nullable<int> KL_12 { get; set; }
        public Nullable<int> KL_13 { get; set; }
        public Nullable<int> KL_14 { get; set; }
        public Nullable<int> KL_15 { get; set; }
        public Nullable<int> KL_16 { get; set; }
        public Nullable<int> KL_17 { get; set; }
        public Nullable<int> KL_18 { get; set; }
        public Nullable<int> KL_19 { get; set; }
        public Nullable<int> KL_20 { get; set; }
    
        public virtual Feature Feature { get; set; }
    }
}
