//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioMexWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyOrder
    {
        public int KO_ID { get; set; }
        public int KO_1 { get; set; }
        public int KO_2 { get; set; }
        public int KO_3 { get; set; }
        public int KO_4 { get; set; }
        public int KO_5 { get; set; }
        public int KO_6 { get; set; }
        public int KO_7 { get; set; }
        public int KO_8 { get; set; }
        public int KO_9 { get; set; }
        public Nullable<int> KO_10 { get; set; }
        public Nullable<int> KO_11 { get; set; }
        public Nullable<int> KO_12 { get; set; }
        public Nullable<int> KO_13 { get; set; }
        public Nullable<int> KO_14 { get; set; }
        public Nullable<int> KO_15 { get; set; }
        public Nullable<int> KO_16 { get; set; }
        public Nullable<int> KO_17 { get; set; }
        public Nullable<int> KO_18 { get; set; }
        public Nullable<int> KO_19 { get; set; }
        public Nullable<int> KO_20 { get; set; }
    
        public virtual Feature Feature { get; set; }
    }
}
