//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioMexWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyPress
    {
        public int KP_ID { get; set; }
        public int KP_1 { get; set; }
        public int KP_2 { get; set; }
        public int KP_3 { get; set; }
        public int KP_4 { get; set; }
        public int KP_5 { get; set; }
        public int KP_6 { get; set; }
        public int KP_7 { get; set; }
        public int KP_8 { get; set; }
        public int KP_9 { get; set; }
        public Nullable<int> KP_10 { get; set; }
        public Nullable<int> KP_11 { get; set; }
        public Nullable<int> KP_12 { get; set; }
        public Nullable<int> KP_13 { get; set; }
        public Nullable<int> KP_14 { get; set; }
        public Nullable<int> KP_15 { get; set; }
        public Nullable<int> KP_16 { get; set; }
        public Nullable<int> KP_17 { get; set; }
        public Nullable<int> KP_18 { get; set; }
        public Nullable<int> KP_19 { get; set; }
        public Nullable<int> KP_20 { get; set; }
    
        public virtual Feature Feature { get; set; }
    }
}
