//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioMexWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyStrokeFeature
    {
        public int KF_ID { get; set; }
        public Nullable<System.DateTime> KF_TimeTaken { get; set; }
        public Nullable<int> KF_TypingSpeed { get; set; }
        public Nullable<int> KF_ShiftClassification { get; set; }
        public int UserUS_ID { get; set; }
    
        public virtual User User { get; set; }
    }
}
