//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioMexWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PairedKey
    {
        public int PK_ID { get; set; }
        public int PK_1 { get; set; }
        public int PK_2 { get; set; }
        public int PK_3 { get; set; }
        public Nullable<int> PK_4 { get; set; }
        public Nullable<int> PK_5 { get; set; }
        public Nullable<int> PK_6 { get; set; }
        public Nullable<int> PK_7 { get; set; }
        public Nullable<int> PK_8 { get; set; }
        public Nullable<int> PK_9 { get; set; }
        public Nullable<int> PK_10 { get; set; }
    
        public virtual Feature Feature { get; set; }
    }
}
