//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioMexWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Features = new HashSet<Feature>();
            this.IdealFeatures = new HashSet<IdealFeature>();
        }
    
        public int US_ID { get; set; }
        public string US_NAME { get; set; }
        public string US_SURNAME { get; set; }
        public string US_USERNAME { get; set; }
        public string US_PASSWORD { get; set; }
        public Nullable<int> US_AGE { get; set; }
        public bool US_UP_TO_DATE { get; set; }
        public System.DateTime US_LAST_LOGGED_IN { get; set; }
        public bool US_IS_ADMIN { get; set; }
    
        public virtual ICollection<Feature> Features { get; set; }
        public virtual ICollection<IdealFeature> IdealFeatures { get; set; }
    }
}
